name: 'Hello World'
description: 'sets up env for test and executes test'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    default: 'World'
  only_setup:
    description: "only sets up python and go"
    default: false
  execute_go_test:
    description: "runs go test"
    default: true
  execute_python_test:
    description: "runs python test"
    default: true
    
runs:
  using: "composite"
  steps:
    - run: pwd
      shell: bash
    - name: wohoo
      run: ls
      shell: bash
    - name: github path
      run: |
        echo ${{ inputs.who-to-greet }}
        echo ${{ inputs.execute-go-test }}
        echo ${{ inputs.execute-python-test }}
      shell: bash
    - if: ${{ inputs.only-setup }}
      run: |
        echo "wohoo not running this"
        echo "thats all!"
      shell: bash
    - if: ${{ inputs.execute-go-test }}
      run: |
        echo "running go tests"
      shell: bash
    - if: ${{ inputs.execute-python-test }}
      run: |
        echo "running python tests"
      shell: bash
