name: random


on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  random:
    runs-on: ubuntu-latest
    
    
    steps:

      # checking out my code
      - name: check var
        run: echo Hello, world!
      - name: checkout
        uses: actions/checkout@v2
      - name: check ci var
        run: echo ${{ github.ci }}
      - name: check ci var
        run: echo $CI
      - name: calling composite 
        uses: ./workflow_helpers
        with:
          who-to-greet: 'Mona'
    
    
